@startuml
sprite $pbkit [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA4E49FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF82DB4FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF54B39FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCDFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFEDDDDDDDDFFFFFFFFFFDDDFFFFFFFFFFFFFFFFFFF
FFFFFFF600000000029FFFFFFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF7000000000002DFFFFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF70000000000000EFFFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF7006FFFFFD60002FFFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF7006FFFFFFFA000AFFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF7006FFFFFFFF5003FFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF7006FFFFFFFFC000FFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF7006FFFFFFFFF000EFF200CFFFFFFFFFFFFFFFFFF
FFFFFFF7006FFFFFFFFE000FFF200CFFCAACFFFFFFFFFFFF
FFFFFFF7006FFFFFFFF7002FFF200B50000006FFFFFFFFFF
FFFFFFF7006FFFFFFFD0008FFF2000000000001DFFFFFFFF
FFFFFFF7006FFFFFFB0001FFFF20000003300001EFFFFFFF
FFFFFFF70013333310000BFFFF200009FFFF80003FFFFFFF
FFFFFFF70000000000009FFFFF2000BFFFFFFA000DFFFFFF
FFFFFFF700000000004DFFFFFF2003FFFFFFFF2006FFFFFF
FFFFFFF7004AAAAABEFFFFFFFF200AFFFFFFFF9003FFFFFF
FFFFFFF7006FFFFFFFFFFFFFFF200CFFFFFFFFA003FFFFFF
FFFFFFF7006FFFFFFFFFFFFFFF2008FFFFFFFF7004FFFFFF
FFFFFFF7006FFFFFFFFFFFFFFF2002FFFFFFFF1008FFFFFF
FFFFFFF7006FFFFFFFFFFFFFFF20007FFFFFF5000EFFFFFF
FFFFFFF7006FFFFFFFFFFFFFFF200004DFFC30006FFFFFFF
FFFFFFF7006FFFFFFFFFFFFFFF20000000000003FFFFFFFF
FFFFFFF7006FFFFFFFFFFFFFFF2002000000004FFFFFFFFF
FFFFFFF6006FFFFFFFFFFFFFFF200CA300003BFFFFFFFFFF
FFFFFFFEDDEFFFFFFFFFFFFFFFDDDFFFFDEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEEFEFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3373B37E35FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD459B3EFA8FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4392B69A26FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

@enduml
